name: "Antispam"
description: "Automatically close spam PRs/issues"
author: "Liam Galvin"
branding:
  icon: 'slash'
  color: 'blue'
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
